### ISSUE TITLE
Jump not working after update

### ISSUE THREAD

**Issue by aldarund** [jdsmith2816/emw#205] opened 2021-05-20 13:01 UTC
**Describe the bug**
Updated from 2.1.2 to 2.2.0 and jump not working anymore. Hitting space do nothing. Checked controls and tried to remap to space again - still not working
Also tried to start new game to check but it just music with black screen and nothing goes on at all

**To Reproduce**
hit space, try to start new game

**Expected behavior**
Jump is working, new game is started fine

**Modlist version** 2.2.0

**Did you add any additional mods?**
Just enabled steam achiev and enderal tracking tools from list and thats all

**Comment by aldarund** [comment] 2021-05-20 15:19
re new game - it works fine and jump work there if start right away after starting game. If load save and than quite to main menu and try to start new game - it will black screen.

So jump is working in new game, but not working in saved game at all. Any hints how to fix jump in save?

**Comment by jdsmith2816** [comment] 2021-05-21 00:35
Oh... I bet my rebind made it into the build.  I have shift set for jump and use space for defensive action in engarde... Try pressing shift.

**Comment by aldarund** [comment] 2021-05-21 09:59
No, shift dont do anything. And as i said its only seems to happen to save files from 2.1.2. And i checked mapping in settings and there is a space for jump

**Comment by Proximae** [comment] 2021-05-21 23:03
I can concur there's an issue with Engarde that makes (at least) jump no longer function. Not sure if that's related but the Quicksave button stopped working aswell. Pressing X to lock on a target (not sure what addon has this implemented), the slow-time effect when using a power attack remains and can't be removed (this is the Combat Focus from Engarde).

Moreso, it seems that Engarde was initially activated (at the start of a new game). Though the MCM menu stopped functioning after hitting the "start Engarde" button. It says "Engarde is starting..." but it never finishes (no Engarde has started msg). Is there a way to have Engarde disabled from the get-go after clean installation and let the user activate it before it starts functioning?

I have used Engarde in the past without issues, but never with EGO combined, maybe the issue lies somewhere there...

Current attempts to fix:
- Re-run MCT_AttackMoveDataPatcher.vbs
- In console: setstage ski_configmanagerinstance 1 --> menu didn't even bother showing up anymore
- Reloads/restarts of the game

The only workaround right now is to reload a save before the bugs start occurring.

Let me know if you want me to do some specific tests

**Comment by Hofbrinclz** [comment] 2021-05-22 19:26
I have a similar issue that started after a new game. It looks like getting staggered/knocked down while jumping breaks jumping for that save file, and the only fix I can find is to reload an older save file.

**Comment by jdsmith2816** [comment] 2021-05-22 19:56
I cannot reproduce the Jump issue in my version of the modlist;  I can't check the official published one right now.  Hopefully that means when I do next update the jump issue will be resolved.

I am, however, able to reproduce the MCM issue and am waiting on tudoro to respond to my question regarding it.

**Comment by Proximae** [comment] 2021-05-23 14:03
The jump issue might only occur when your character gets flung back (ragdoll effect where you lose control for a couple seconds). I wasn't able to reproduce the jump issue but wasn't flung around either. The MCM issue crashes 100% of the time I tried it.

When starting a new game, you can change the Engarde keybindings, but after that I would advise not touching any of the other settings or opening the MCM menu if you want it to remain working. The jumping bug after ragdoll might still occur though

**Comment by Proximae** [comment] 2021-05-24 22:22
Was not able to reproduce the jump issue (so far) but I managed to get the slow-time effect bug when using or blocking a power attack. This is whenever Combat Focus was set from Toggle to Always Active. Once the bug occurs, the player can't regain normal functionality (the entire game is perma-slowed)

**Comment by aldarund** [comment] 2021-05-24 22:37
in 2.3.0 i was able to fix it. It happens when engarde not started. So in save from 2.2.0 where jump was broken i was need to go to mcm engarde and hit activate button - after it jump worked. If i load 2.1.0 save in 2.3.0 - engarde starts automatically and jump works after it started

**Comment by jdsmith2816** [comment] 2021-05-25 03:07
As the issue with jump appears to be corrected in the latest build I'm going to go ahead and close this ticket.  Could you please submit a separate one to track the slowtime issue?

**Closed by jdsmith2816** 2021-05-25 03:07 UTC
