### ISSUE TITLE
Graphical glitch - head different skin texture than body of corpse in Golden Cycle quest

### ISSUE THREAD

**Issue by Lazasar** [jdsmith2816/emw#29] opened 2020-05-27 12:36 UTC
![image](https://user-images.githubusercontent.com/18401877/83019475-ad529900-a02f-11ea-93a1-441b75ea2733.png)

**Comment by kratores85** [comment] 2020-09-16 13:31
Duplicate of #70

**Comment by jdsmith2816** [comment] 2021-02-08 17:53
This is no longer an issue for the upcoming release.

**Closed by jdsmith2816** 2021-02-08 17:53 UTC
