### ISSUE TITLE
Occasionally crashing in the Player Owned house in the Ark Marketplace.

### ISSUE THREAD

**Issue by Lazasar** [jdsmith2816/emw#10] opened 2020-05-24 04:53 UTC
It doesn't always happen. When it does, it is shortly after entering the house, I  think only after paying the 300 pennies for the furniture.

**Comment by jdsmith2816** [comment] 2020-06-04 20:26
I'm unable to reproduce this in 1.0.3 which included an update to the player home to fix various bugs.  I'm going to close this but feel free to reopen it if you continue to experience the issue.  Now that I have the player home in my game I'll keep an eye out as well.

**Closed by jdsmith2816** 2020-06-04 20:26 UTC
